// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX-PxeZbRNQ_skE7O4rY6zyLwRQIDAd7o',
    appId: '1:797179525518:web:812db4b290407cd2fb0cdf',
    messagingSenderId: '797179525518',
    projectId: 'snack-49e96',
    authDomain: 'snack-49e96.firebaseapp.com',
    storageBucket: 'snack-49e96.appspot.com',
    measurementId: 'G-K2D6YZQNH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABxjSvvDPi2KZOH7LLJc0WYWfhdOnPLJM',
    appId: '1:797179525518:android:72874a3c64beaf83fb0cdf',
    messagingSenderId: '797179525518',
    projectId: 'snack-49e96',
    storageBucket: 'snack-49e96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKNoyqfiwDsSKvoa_W1jMMx1iCebv96WU',
    appId: '1:797179525518:ios:7f72e3271f8675a0fb0cdf',
    messagingSenderId: '797179525518',
    projectId: 'snack-49e96',
    storageBucket: 'snack-49e96.appspot.com',
    iosClientId: '797179525518-f9rjdsr3jadp61e02j60abp6su0ac42e.apps.googleusercontent.com',
    iosBundleId: 'com.example.snack',
  );
}
